language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-numpy python-gdal python-shapely python-pyshp

install:
  - python setup.py install

script:
  - python -m unittest discover test
