language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
install:
  - "pip install numpy"
  - "pip install shapely"
  - "pip install pyshp"
  - "pip install GDAL"
  - "python setup.py install"
script: "python -m unittest discover test/"